<#
.SYNOPSIS
    Create HTML report.

.DESCRIPTION
    Creates a formatted HTML report from CSV input.

.AUTHOR
    Muhammad Yasir

.CREATED
    2026-05-15

.COPYRIGHT
    Copyright (c) 2026 Muhammad Yasir. All rights reserved.

.PARAMETER CsvPath
    The path to the CSV file that will be converted into an HTML report.

.PARAMETER OutputPath
    The path where the generated HTML report will be saved.

.PARAMETER Title
    The title displayed in the HTML report.

.EXAMPLE
    New-M365HtmlReport -CsvPath ".\reports\csv\m365-users.csv"

.EXAMPLE
    New-M365HtmlReport `
        -CsvPath ".\reports\csv\m365-users.csv" `
        -OutputPath ".\reports\html\m365-users.html" `
        -Title "Microsoft 365 Users Report"

.NOTES
    Run PowerShell as Administrator when local or Microsoft 365 permissions are required.
#>

function New-M365HtmlReport {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [ValidateScript({
            if (-not (Test-Path -Path $_ -PathType Leaf)) {
                throw "CSV file not found: $_"
            }

            if ([System.IO.Path]::GetExtension($_) -ne ".csv") {
                throw "Input file must be a CSV file: $_"
            }

            return $true
        })]
        [string]$CsvPath,

        [Parameter(Mandatory = $false)]
        [ValidateNotNullOrEmpty()]
        [string]$OutputPath = ".\reports\html\report.html",

        [Parameter(Mandatory = $false)]
        [ValidateNotNullOrEmpty()]
        [string]$Title = "M365 Toolkit Report"
    )

    begin {
        $ErrorActionPreference = "Stop"

        $outputDirectory = Split-Path -Path $OutputPath -Parent

        if ($outputDirectory -and -not (Test-Path -Path $outputDirectory)) {
            New-Item `
                -ItemType Directory `
                -Path $outputDirectory `
                -Force | Out-Null
        }

        $generatedAt = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    }

    process {
        try {
            $data = Import-Csv -Path $CsvPath -ErrorAction Stop

            if (-not $data) {
                Write-Warning "CSV file contains no data: $CsvPath"
            }

            $style = @"
<style>
    body {
        font-family: Segoe UI, Arial, sans-serif;
        margin: 24px;
        background-color: #f5f7fa;
        color: #1f2937;
    }

    h1 {
        color: #111827;
        margin-bottom: 4px;
    }

    .meta {
        color: #6b7280;
        margin-bottom: 24px;
    }

    table {
        border-collapse: collapse;
        width: 100%;
        background-color: #ffffff;
        box-shadow: 0 1px 3px rgba(0, 0, 0, 0.08);
    }

    th {
        background-color: #111827;
        color: #ffffff;
        text-align: left;
        padding: 10px;
        font-size: 13px;
    }

    td {
        border-bottom: 1px solid #e5e7eb;
        padding: 8px 10px;
        font-size: 13px;
        vertical-align: top;
    }

    tr:hover {
        background-color: #f3f4f6;
    }

    .footer {
        margin-top: 24px;
        color: #6b7280;
        font-size: 12px;
    }
</style>
"@

            $preContent = @"
<h1>$Title</h1>
<p class="meta">Generated: $generatedAt</p>
"@

            $postContent = @"
<p class="footer">Generated by M365 Toolkit.</p>
"@

            $data |
                ConvertTo-Html `
                    -Title $Title `
                    -Head $style `
                    -PreContent $preContent `
                    -PostContent $postContent |
                Set-Content `
                    -Path $OutputPath `
                    -Encoding UTF8

            Write-Host "HTML report created successfully: $OutputPath" -ForegroundColor Green

            Get-Item -Path $OutputPath
        }
        catch {
            Write-Error "Failed to create HTML report from '$CsvPath'. $($_.Exception.Message)"
        }
    }
}